import {
  faBolt,
  faCloud,
  faCloudMeatball,
  faCloudRain,
  faCloudShowersHeavy,
  faSmog,
  faSnowflake,
  faSun,
  IconDefinition,
} from "@fortawesome/free-solid-svg-icons";

export const WEATHER_URL = "https://api.open-meteo.com/v1/forecast";

export const WEATHER_ICONS: Record<string, IconDefinition> = {
  0: faSun,
  1: faCloud,
  2: faCloud,
  3: faCloud,
  45: faSmog,
  48: faSmog,
  51: faCloudRain,
  53: faCloudRain,
  55: faCloudRain,
  56: faCloudRain,
  57: faCloudRain,
  61: faCloudRain,
  63: faCloudRain,
  65: faCloudRain,
  66: faSnowflake,
  67: faSnowflake,
  71: faSnowflake,
  73: faSnowflake,
  75: faSnowflake,
  77: faCloudMeatball,
  80: faCloudShowersHeavy,
  81: faCloudShowersHeavy,
  82: faCloudShowersHeavy,
  85: faSnowflake,
  86: faSnowflake,
  95: faBolt,
  96: faBolt,
  99: faBolt,
};
